checks:pylint:
  before_script:
  - sudo dnf install -y python3-pip
  - pip3 install --quiet -r ci/requirements.txt
  script:
  - PYTHONPATH="test-packages:$PYTHONPATH" python3 -m pylint qubesmanager
  stage: checks
include:
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
